### ISSUE TITLE
复制不了可用模型或一致模型

### ISSUE THREAD

**Issue by toniexly** [QAbot-zh/query-key#14]
试过ff和edge均不行。。是否提供alternative方法。
另外建议结果模型不分页？可滚动选择复制

**Comment by QAbot-zh** [comment]
不会呀，我在 edge 上测试了可以复制的，是自己部署的吗，在 https://check.crond.dev 这个网站上也无法复制吗，检查一下网站设置，同时看看控制台的输出信息

**Comment by penginman** [comment]
自己docker部署的，chrome浏览器和edge，复制一致模型和可用模型控制台分别报错
-----------------------------------
 TypeError: Cannot read properties of undefined (reading 'writeText')
    at $t (:2339/assets/index-C5vpLBi8.js:55:8398)
    at n.onClick.t.<computed>.t.<computed> (:2339/assets/index-C5vpLBi8.js:55:16953)
    at nl (:2339/assets/vendor-Db-y4AGu.js:13:38)
    at Nr (:2339/assets/vendor-Db-y4AGu.js:13:109)
    at HTMLAnchorElement.r (:2339/assets/vendor-Db-y4AGu.js:17:7550)
Y4 @ :2339/assets/vendor-Db-y4AGu.js:13
Nf @ :2339/assets/vendor-Db-y4AGu.js:13
nl @ :2339/assets/vendor-Db-y4AGu.js:13
Nr @ :2339/assets/vendor-Db-y4AGu.js:13
r @ :2339/assets/vendor-Db-y4AGu.js:17
-----------------------------------
 TypeError: Cannot read properties of undefined (reading 'writeText')
    at $t (:2339/assets/index-C5vpLBi8.js:55:8398)
    at n.onClick.t.<computed>.t.<computed> (:2339/assets/index-C5vpLBi8.js:55:17073)
    at nl (:2339/assets/vendor-Db-y4AGu.js:13:38)
    at Nr (:2339/assets/vendor-Db-y4AGu.js:13:109)
    at HTMLAnchorElement.r (:2339/assets/vendor-Db-y4AGu.js:17:7550)
